name: Node.js Package

on:
  release:
    types: [created, published]
  workflow_dispatch:

jobs:

  install:
    runs-on: ubuntu-20.04
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 10.24.1

      - name: Restore npm cache
        id: npm-cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies (if cache miss)
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm install

  build-and-test:
    needs: install
    runs-on: ubuntu-20.04
    env:
      NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 10.24.1
      
      - name: Restore npm cache
        id: npm-cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies (if cache miss)
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm install

      - run: npm run build
      - run: npm run test

  publish-gpr:
    needs: build-and-test
    runs-on: ubuntu-20.04
    permissions:
      packages: write
      contents: read
    env:
      NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 10.24.1
          registry-url: https://npm.pkg.github.com/
          
      - name: Restore npm cache
        id: npm-cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies (if cache miss)
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm install
        
      - run: npm publish
